# /// script
# requires-python = ">=3.10"
# dependencies = ["pandas", "numpy", "scipy"]
# ///
"""Check the primary behavioral effects of Anlló et al. (2024), Comparing
experience- and description-based economic preferences across 11 countries,
Nat. Hum. Behav. 8, 1554-1567, against any dataset in the Psych-301 unified
schema (see schema.md).

Effects tested:
- experience_learning_above_chance (exp0): in the experience-based bandit (learning
  phase) participants choose the value-maximizing option more often than chance;
  per-participant mean correct rate > 0.5 (one-sample t-test).
- experience_context_transfer_decrement (exp0): the paper's central context-sensitivity
  claim — suboptimal decisions arise when value ranges are context-manipulated; the
  per-participant correct rate in the magnitude-asymmetric transfer conditions (5-8)
  is lower than in the symmetric learning conditions (1-4) (paired t-test).
- description_probability_weighting (exp1): in the description-based lottery task,
  choice of the risky [p,10] option increases with its outcome probability p
  (inverse-S probability weighting); per-participant risky-choice rate at high p
  (conditions 11-12: p=.75/1) exceeds that at low p (conditions 9-10: p=.25/.5)
  (paired t-test).
"""
from __future__ import annotations

import argparse

import numpy as np
import pandas as pd
from scipy import stats

EXPERIMENTS = ["exp0", "exp1"]


def load_data(sources: dict[str, str] | None = None) -> dict[str, pd.DataFrame]:
    """Returns {experiment_name: DataFrame}.

    sources: optional {experiment_name: csv_path} override. With no overrides,
    loads ./{exp}.csv from CWD — `cd` into a checkout of the dataset repo (or
    pass --<exp> path on the CLI) before running.

    Required columns per experiment:
      exp0: participant_id, phase, condition, correct
      exp1: participant_id, condition, response, Magnitude2, Proba2
    """
    sources = sources or {}
    return {exp: pd.read_csv(sources.get(exp, f"./{exp}.csv")) for exp in EXPERIMENTS}


def check_experience_learning_above_chance(data: dict[str, pd.DataFrame]) -> dict:
    """\"Our findings show that context sensitivity was present in all 11 countries.\"
    In the experience task participants learned to choose the value-maximizing option
    (accuracy well above chance) — Anlló et al. (2024), p.1554, Abstract; Behavioural
    results/Fig. 2."""
    df = data["exp0"]
    learn = df[df["phase"] == "learning"]
    per = learn.groupby("participant_id")["correct"].mean()
    t, p = stats.ttest_1samp(per, 0.5)
    reproduced = bool(p < 0.05 and per.mean() > 0.5)
    return {
        "effect_name": "experience_learning_above_chance",
        "experiment": "exp0",
        "original_effect_size": 0.5,  # above-chance threshold (chance = .5)
        "effect_size": float(per.mean() - 0.5),
        "reproduced": reproduced,
    }


def check_experience_context_transfer_decrement(data: dict[str, pd.DataFrame]) -> dict:
    """\"Suboptimal decisions generated by context manipulation were not explained by
    risk aversion.\" Correct rate is lower in the magnitude-asymmetric transfer
    conditions (5-8) than in the symmetric learning conditions (1-4), the signature
    of context-dependent value encoding — Anlló et al. (2024), p.1554, Abstract;
    Fig. 2."""
    df = data["exp0"]
    learn = df[(df["phase"] == "learning") & (df["condition"].isin([1, 2, 3, 4]))]
    trans = df[(df["phase"] == "transfer") & (df["condition"].isin([5, 6, 7, 8]))]
    lp = learn.groupby("participant_id")["correct"].mean()
    tp = trans.groupby("participant_id")["correct"].mean()
    both = pd.DataFrame({"learn": lp, "trans": tp}).dropna()
    t, p = stats.ttest_rel(both["trans"], both["learn"])
    diff = float(both["trans"].mean() - both["learn"].mean())
    reproduced = bool(p < 0.05 and diff < 0)
    return {
        "effect_name": "experience_context_transfer_decrement",
        "experiment": "exp0",
        "original_effect_size": -0.05,  # paper reports a negative context effect
        "effect_size": diff,
        "reproduced": reproduced,
    }


def check_description_probability_weighting(data: dict[str, pd.DataFrame]) -> dict:
    """\"risk aversion significantly differed across countries\" in the description-based
    (lottery) task; risky [p,10] choices rise with outcome probability p, reflecting
    probability weighting — Anlló et al. (2024), p.1554, Abstract; Behavioural results."""
    df = data["exp1"]
    df = df.copy()
    df["risky_right"] = df["Magnitude2"] == 10
    df["chose_risky"] = np.where(df["risky_right"], df["response"] == 1, df["response"] == -1)
    lo = df[df["condition"].isin([9, 10])].groupby("participant_id")["chose_risky"].mean()
    hi = df[df["condition"].isin([11, 12])].groupby("participant_id")["chose_risky"].mean()
    both = pd.DataFrame({"lo": lo, "hi": hi}).dropna()
    t, p = stats.ttest_rel(both["hi"], both["lo"])
    diff = float(both["hi"].mean() - both["lo"].mean())
    reproduced = bool(p < 0.05 and diff > 0)
    return {
        "effect_name": "description_probability_weighting",
        "experiment": "exp1",
        "original_effect_size": 0.2,  # risky-choice rate rises with p (approx.)
        "effect_size": diff,
        "reproduced": reproduced,
    }


EFFECTS = [
    check_experience_learning_above_chance,
    check_experience_context_transfer_decrement,
    check_description_probability_weighting,
]


def run_analysis(sources: dict[str, str] | None = None) -> list[dict]:
    """One result dict per effect in EFFECTS order. No printing — pure return value
    so downstream simulators / model evaluators can call this programmatically."""
    data = load_data(sources)
    return [fn(data) for fn in EFFECTS]


def main() -> None:
    ap = argparse.ArgumentParser()
    for exp in EXPERIMENTS:
        ap.add_argument(f"--{exp}", default=None, help=f"CSV path for {exp}; defaults to ./{exp}.csv in CWD")
    args = ap.parse_args()
    sources = {exp: getattr(args, exp) for exp in EXPERIMENTS if getattr(args, exp)}
    for exp in EXPERIMENTS:
        if exp in sources:
            print(f"{exp}: {sources[exp]}")
        else:
            print(f"{exp}: (default — local ./{exp}.csv)")
    results = run_analysis(sources)
    w = max(len(r["effect_name"]) for r in results)
    print()
    print(f"{'effect':<{w}}  {'exp':<4}  {'orig':>10}  {'this':>10}  reproduced")
    for r in results:
        print(f"{r['effect_name']:<{w}}  {r['experiment']:<4}  "
              f"{r['original_effect_size']:>10.3f}  {r['effect_size']:>10.3f}  "
              f"{'YES' if r['reproduced'] else 'NO'}")


if __name__ == "__main__":
    main()
