# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy", "pandas", "tqdm"]
# ///
"""Text simulator for exp0 of ``Hugging-Brain/gnther_2022_patterns``,
format-identical to the repo's ``transcripts0.jsonl``.

``uv run simulate0.py -n 3`` smoke-tests with a uniform-random agent; or import
the class and pass your own ``agent(prompt, choice_options)``.
"""
import argparse
import random

import numpy as np
import pandas as pd
from tqdm import tqdm

RELATIONS = [
    ("H_about_M",      "the head is about the modifier"),
    ("H_by_M",         "the head is by the modifier"),
    ("H_caused_by_M",  "the head is caused by the modifier"),
    ("H_causes_M",     "the head causes the modifier"),
    ("H_during_M",     "the head is during the modifier"),
    ("H_for_M",        "the head is for the modifier"),
    ("H_from_M",       "the head is from the modifier"),
    ("H_has_M",        "the head has the modifier"),
    ("H_is_M",         "the head is the modifier"),
    ("H_location_is_M","the head is located at the modifier"),
    ("H_made_of_M",    "the head is made of the modifier"),
    ("H_makes_M",      "the head makes the modifier"),
    ("H_used_by_M",    "the head is used by the modifier"),
    ("H_uses_M",       "the head uses the modifier"),
    ("M_has_H",        "the modifier has the head"),
    ("M_location_is_H","the modifier is located at the head"),
]
LETTERS = "ABCDEFGHIJKLMNOP"

PHRASE = {
    "H_about_M": "ABOUT", "H_by_M": "BY", "H_caused_by_M": "CAUSED BY",
    "H_causes_M": "CAUSES", "H_during_M": "DURING", "H_for_M": "FOR",
    "H_from_M": "DERIVED FROM", "H_has_M": "HAS", "H_is_M": "IS",
    "H_location_is_M": "LOCATION IS", "H_made_of_M": "MADE OF",
    "H_makes_M": "MAKES", "H_used_by_M": "USED BY", "H_uses_M": "USES",
    "M_has_H": "HAS", "M_location_is_H": "LOCATION IS",
}

NOVEL = [
    'rear stove',
    'protein buy',
    'fine father',
    'mouse gown',
    'cable bush',
    'salt mayor',
    'chair bin',
    'team ball',
    'wood brush',
    'tin fish',
    'paint coat',
    'lodging singer',
    'back weed',
    'pony comb',
    'fear stain',
    'turbo fusion',
    'west scheme',
    'boat pipe',
    'black rink',
    'river hand',
    'sling party',
    'scare format',
    'rail table',
    'litter matter',
    'club pond',
    'worm street',
    'ice meat',
    'bed tape',
    'girl boy',
    'girl worker',
    'rail site',
    'back wheat',
    'set weed',
    'moon bed',
    'mouse storm',
    'folk loom',
    'char fry',
    'wood cab',
    'fair ligand',
    'brown rating',
    'search trick',
    'militia enemy',
    'sword craft',
    'song boy',
    'opening mass',
    'paint window',
    'silver teller',
    'time fish',
    'descent sell',
    'herring group',
    'rail gate',
    'ship port',
    'sand fish',
    'margin plank',
    'fish water',
    'bore chase',
    'base bike',
    'grand roll',
    'sail wind',
    'passion wood',
    'center piper',
    'lighter elf',
    'south plant',
    'pick sled',
    'barn shaft',
    'chit stuff',
    'tractor photon',
    'time port',
    'south mile',
    'kin study',
    'battle quake',
    'stem hockey',
    'draw lark',
    'sand stock',
    'head cloth',
    'boat screen',
    'indie punk',
    'euro linen',
    'rain pond',
    'cross fish',
    'waist force',
    'hand water',
    'bridge mill',
    'needle leave',
    'rail hop',
    'home pile',
    'flow beat',
    'husband raid',
    'wicket dye',
    'gene tender',
    'chair bike',
    'norman cam',
    'fire quake',
    'vicar warp',
    'fact sail',
    'girl wife',
    'fire mill',
    'command loop',
    'half writer',
    'slip mason',
    'setting oxygen',
    'dead storey',
    'window hole',
    'brick shadow',
    'take crest',
    'goal game',
    'patron stays',
    'beach stack',
    'torpedo wit',
    'set boat',
    'saw meat',
    'level trunk',
    'band hole',
    'sound craft',
    'ship head',
    'slap chord',
    'web engine',
    'crank pump',
    'high robin',
    'major poster',
    'techno lapse',
    'chapter spot',
    'dish panel',
    'crew day',
    'chair soil',
    'buffet tide',
    'school mill',
    'sand ache',
    'music serial',
    'bed maid',
    'battle note',
    'girl man',
    'white rush',
    'harvest cycle',
    'farm flour',
    'boat ship',
    'ship club',
    'toe bridge',
    'number sense',
    'broad driver',
    'body girl',
    'copper wood',
    'soul mother',
    'comic ends',
    'farm mill',
    'weather sail',
    'process tower',
    'guess county',
    'night ship',
    'mile set',
    'sage medal',
    'rail piece',
    'fort shape',
    'brick steak',
    'loin robe',
    'sand quake',
    'meadow luck',
    'band rock',
    'hearth belly',
    'mast hoe',
    'byte miner',
    'cash summer',
    'beef broker',
    'sea buoy',
    'bob load',
    'rose mill',
    'back boat',
    'hunter poll',
    'bag street',
    'info finch',
    'skate band',
    'birth wife',
    'consul son',
    'milk friend',
    'switch job',
    'tree soil',
    'use record',
    'ion riding',
    'lunch day',
    'win slot',
    'day fish',
    'saw fuel',
    'tram fill',
    'special owl',
    'shop room',
    'rein shine',
    'strait timer',
    'bubble step',
    'gilt round',
    'bog term',
    'shin click',
    'cheese road',
    'anchor domain',
    'hair dress',
    'meeting jar',
    'sea storm',
    'dance swing',
    'jet giving',
    'goal coach',
    'waist set',
    'sand tan',
    'review onset',
    'wine button',
    'folk line',
    'school post',
    'fish flour',
    'rifle sale',
    'wind stack',
    'dove width',
    'plot curve',
    'shop house',
    'yard ship',
    'sword bird',
    'lithium pad',
    'fog solver',
    'drama fellow',
    'saw note',
    'launch jerk',
    'pigeon loss',
    'log server',
    'manor lot',
    'snow mat',
    'cheese meat',
    'pillow lobe',
    'player swap',
    'fuel desk',
    'tie fly',
    'word buyer',
    'run scarf',
    'lumber mining',
    'screw decker',
    'captain vessel',
    'push lady',
    'stair line',
    'figure goblin',
    'ram being',
    'asylum hiker',
    'cafe pop',
    'outside hawk',
    'boat day',
    'boat car',
    'mean dragon',
    'jig root',
    'teacher red',
    'breadth act',
    'altar tee',
    'barn mill',
    'career sort',
    'prince stitch',
    'road town',
    'candle cake',
    'ankle cord',
    'middle action',
    'fuel coal',
    'road path',
    'holly dealer',
    'score finish',
    'fist medium',
    'trend hen',
    'spell energy',
    'drug box',
    'draw block',
    'grass soil',
    'dot deck',
    'hook people',
    'lamp foot',
    'form fowl',
    'dog boat',
    'cloud fit',
    'october going',
    'tail mill',
    'square gas',
    'grave pond',
    'june scotch',
    'pitch view',
    'sword right',
    'cloak robe',
    'leg lark',
    'disease louse',
    'dive essay',
    'camp end',
    'stand quake',
    'film bed',
    'razor story',
    'bag power',
    'tow motor',
    'january caste',
    'goal man',
    'paint paper',
    'custom dad',
    'life girl',
    'clergy church',
    'script flat',
    'file pit',
    'fact broker',
    'pack stand',
    'final scorer',
    'livery world',
    'trip series',
    'part brush',
    'contra making',
    'sword well',
    'censor child',
    'pill blue',
    'hog case',
    'cliff sphere',
    'epoch earner',
    'wood fish',
    'news yard',
    'wish bolt',
    'east north',
    'iron radish',
    'worm gull',
    'pay copier',
    'case robe',
    'sand soil',
    'fact soil',
    'thumb bird',
    'snow ice',
    'girl woman',
    'band buoy',
    'alder mind',
    'folk way',
    'label delay',
    'fisher dryer',
    'jelly effect',
    'plain tennis',
    'stair room',
    'folk hop',
    'beach kind',
    'ski skiing',
    'glow seater',
    'synth make',
    'cheese meal',
    'task wool',
    'season league',
    'gall top',
    'path guard',
    'life bulb',
    'mouse dog',
    'cinema arch',
    'role order',
    'time comb',
    'sea flour',
    'flour powder',
    'feast taking',
    'stair gown',
    'dash second',
    'drug bed',
    'rip surf',
    'side quake',
    'pinch share',
    'wood mill',
    'low think',
    'news bridge',
    'start shade',
    'coal line',
    'feather bound',
    'brick mill',
    'sail ship',
    'cross gear',
    'drive phone',
    'fighter piece',
    'straw gain',
    'nick vision',
    'corner lark',
    'sham lead',
    'strap jacket',
    'leather patch',
    'kill tenant',
    'draw flight',
    'sugar owner',
    'waist dress',
    'lark case',
    'dip brace',
    'head boat',
    'row glider',
    'maple region',
    'nit led',
    'movie teaser',
    'bishop lily',
    'safe flower',
    'neck bulb',
    'ape seed',
    'god shock',
    'photo pond',
    'unity pager',
    'mail soil',
    'waist press',
    'print well',
    'boat sled',
    'tea food',
    'pub result',
    'short racing',
    'farm room',
    'font giver',
    'stair door',
    'chair screen',
    'hair time',
    'bid seeker',
    'shuffle quest',
    'centre grouse',
    'tooth end',
    'snap nickel',
    'proof shaft',
    'public goon',
    'stair cloth',
    'crew ship',]

CATCH = [
    'snow man',
    'stone ware',
    'tea time',
    'sweat band',]

LISTS = (  # the eight 51-item lists recovered from exp0.csv, in order of first appearance
    (
        'back weed', 'back wheat', 'bed tape',
        'black rink', 'boat pipe', 'brown rating',
        'cable bush', 'chair bin', 'char fry',
        'club pond', 'descent sell', 'fair ligand',
        'fear stain', 'fine father', 'folk loom',
        'girl boy', 'girl worker', 'herring group',
        'ice meat', 'litter matter', 'lodging singer',
        'militia enemy', 'moon bed', 'mouse gown',
        'mouse storm', 'opening mass', 'paint coat',
        'paint window', 'pony comb', 'protein buy',
        'rail gate', 'rail site', 'rail table',
        'rear stove', 'river hand', 'salt mayor',
        'scare format', 'search trick', 'set weed',
        'silver teller', 'sling party', 'song boy',
        'sword craft', 'team ball', 'time fish',
        'tin fish', 'turbo fusion', 'west scheme',
        'wood brush', 'wood cab', 'worm street',
    ),
    (
        'barn shaft', 'base bike', 'battle quake',
        'boat screen', 'bore chase', 'bridge mill',
        'center piper', 'chair bike', 'chit stuff',
        'command loop', 'cross fish', 'dead storey',
        'draw lark', 'euro linen', 'fact sail',
        'fire mill', 'fire quake', 'fish water',
        'flow beat', 'gene tender', 'girl wife',
        'grand roll', 'half writer', 'hand water',
        'head cloth', 'home pile', 'husband raid',
        'indie punk', 'kin study', 'lighter elf',
        'margin plank', 'needle leave', 'norman cam',
        'passion wood', 'pick sled', 'rail hop',
        'rain pond', 'sail wind', 'sand fish',
        'sand stock', 'setting oxygen', 'ship port',
        'slip mason', 'south mile', 'south plant',
        'stem hockey', 'time port', 'tractor photon',
        'vicar warp', 'waist force', 'wicket dye',
    ),
    (
        'band hole', 'battle note', 'beach stack',
        'bed maid', 'boat ship', 'body girl',
        'brick shadow', 'broad driver', 'buffet tide',
        'chair soil', 'chapter spot', 'comic ends',
        'copper wood', 'crank pump', 'crew day',
        'dish panel', 'farm flour', 'farm mill',
        'fort shape', 'girl man', 'goal game',
        'guess county', 'harvest cycle', 'high robin',
        'level trunk', 'major poster', 'mile set',
        'music serial', 'night ship', 'number sense',
        'patron stays', 'process tower', 'rail piece',
        'sage medal', 'sand ache', 'saw meat',
        'school mill', 'set boat', 'ship club',
        'ship head', 'slap chord', 'soul mother',
        'sound craft', 'take crest', 'techno lapse',
        'toe bridge', 'torpedo wit', 'weather sail',
        'web engine', 'white rush', 'window hole',
    ),
    (
        'anchor domain', 'back boat', 'bag street',
        'band rock', 'beef broker', 'birth wife',
        'bob load', 'bog term', 'brick steak',
        'bubble step', 'byte miner', 'cash summer',
        'cheese road', 'consul son', 'dance swing',
        'day fish', 'folk line', 'gilt round',
        'goal coach', 'hair dress', 'hearth belly',
        'hunter poll', 'info finch', 'ion riding',
        'jet giving', 'loin robe', 'lunch day',
        'mast hoe', 'meadow luck', 'meeting jar',
        'milk friend', 'rein shine', 'review onset',
        'rose mill', 'sand quake', 'sand tan',
        'saw fuel', 'sea buoy', 'sea storm',
        'shin click', 'shop room', 'skate band',
        'special owl', 'strait timer', 'switch job',
        'tram fill', 'tree soil', 'use record',
        'waist set', 'win slot', 'wine button',
    ),
    (
        'altar tee', 'ankle cord', 'asylum hiker',
        'barn mill', 'boat car', 'boat day',
        'breadth act', 'cafe pop', 'candle cake',
        'captain vessel', 'career sort', 'cheese meat',
        'dove width', 'drama fellow', 'figure goblin',
        'fish flour', 'fog solver', 'fuel coal',
        'fuel desk', 'jig root', 'launch jerk',
        'lithium pad', 'log server', 'lumber mining',
        'manor lot', 'mean dragon', 'middle action',
        'outside hawk', 'pigeon loss', 'pillow lobe',
        'player swap', 'plot curve', 'prince stitch',
        'push lady', 'ram being', 'rifle sale',
        'road path', 'road town', 'run scarf',
        'saw note', 'school post', 'screw decker',
        'shop house', 'snow mat', 'stair line',
        'sword bird', 'teacher red', 'tie fly',
        'wind stack', 'word buyer', 'yard ship',
    ),
    (
        'bag power', 'camp end', 'censor child',
        'clergy church', 'cliff sphere', 'cloak robe',
        'cloud fit', 'contra making', 'custom dad',
        'disease louse', 'dive essay', 'dog boat',
        'dot deck', 'draw block', 'drug box',
        'fact broker', 'file pit', 'film bed',
        'final scorer', 'fist medium', 'form fowl',
        'goal man', 'grass soil', 'grave pond',
        'hog case', 'holly dealer', 'hook people',
        'january caste', 'june scotch', 'lamp foot',
        'leg lark', 'life girl', 'livery world',
        'october going', 'pack stand', 'paint paper',
        'part brush', 'pill blue', 'pitch view',
        'razor story', 'score finish', 'script flat',
        'spell energy', 'square gas', 'stand quake',
        'sword right', 'sword well', 'tail mill',
        'tow motor', 'trend hen', 'trip series',
    ),
    (
        'alder mind', 'band buoy', 'beach kind',
        'case robe', 'cheese meal', 'cinema arch',
        'coal line', 'dash second', 'drug bed',
        'east north', 'epoch earner', 'fact soil',
        'feast taking', 'fisher dryer', 'flour powder',
        'folk hop', 'folk way', 'gall top',
        'girl woman', 'glow seater', 'iron radish',
        'jelly effect', 'label delay', 'life bulb',
        'low think', 'mouse dog', 'news bridge',
        'news yard', 'path guard', 'pay copier',
        'pinch share', 'plain tennis', 'rip surf',
        'role order', 'sand soil', 'sea flour',
        'season league', 'side quake', 'ski skiing',
        'snow ice', 'stair gown', 'stair room',
        'start shade', 'synth make', 'task wool',
        'thumb bird', 'time comb', 'wish bolt',
        'wood fish', 'wood mill', 'worm gull',
    ),
    (
        'ape seed', 'bid seeker', 'bishop lily',
        'boat sled', 'brick mill', 'centre grouse',
        'chair screen', 'corner lark', 'crew ship',
        'cross gear', 'dip brace', 'draw flight',
        'drive phone', 'farm room', 'feather bound',
        'fighter piece', 'font giver', 'god shock',
        'hair time', 'head boat', 'kill tenant',
        'lark case', 'leather patch', 'mail soil',
        'maple region', 'movie teaser', 'neck bulb',
        'nick vision', 'nit led', 'photo pond',
        'print well', 'proof shaft', 'pub result',
        'public goon', 'row glider', 'safe flower',
        'sail ship', 'sham lead', 'short racing',
        'shuffle quest', 'snap nickel', 'stair cloth',
        'stair door', 'strap jacket', 'straw gain',
        'sugar owner', 'tea food', 'tooth end',
        'unity pager', 'waist dress', 'waist press',
    ),
)

STIM_TYPE = {
    'rear stove': 'outtrain',
    'protein buy': 'outtrain',
    'fine father': 'outtrain',
    'mouse gown': 'intrain',
    'cable bush': 'outtrain',
    'salt mayor': 'outtrain',
    'chair bin': 'intrain',
    'team ball': 'intrain',
    'wood brush': 'intrain',
    'tin fish': 'intrain',
    'paint coat': 'intrain',
    'lodging singer': 'outtrain',
    'back weed': 'intrain',
    'pony comb': 'intrain',
    'fear stain': 'outtrain',
    'turbo fusion': 'outtrain',
    'west scheme': 'outtrain',
    'boat pipe': 'intrain',
    'black rink': 'outtrain',
    'river hand': 'intrain',
    'sling party': 'outtrain',
    'scare format': 'outtrain',
    'rail table': 'intrain',
    'litter matter': 'outtrain',
    'club pond': 'intrain',
    'worm street': 'intrain',
    'ice meat': 'intrain',
    'bed tape': 'intrain',
    'girl boy': 'intrain',
    'girl worker': 'intrain',
    'rail site': 'intrain',
    'back wheat': 'intrain',
    'set weed': 'intrain',
    'moon bed': 'intrain',
    'mouse storm': 'intrain',
    'folk loom': 'intrain',
    'char fry': 'outtrain',
    'wood cab': 'intrain',
    'fair ligand': 'outtrain',
    'brown rating': 'outtrain',
    'search trick': 'outtrain',
    'militia enemy': 'outtrain',
    'sword craft': 'intrain',
    'song boy': 'intrain',
    'opening mass': 'outtrain',
    'paint window': 'intrain',
    'silver teller': 'outtrain',
    'time fish': 'intrain',
    'descent sell': 'outtrain',
    'herring group': 'outtrain',
    'rail gate': 'intrain',
    'ship port': 'intrain',
    'sand fish': 'intrain',
    'margin plank': 'outtrain',
    'fish water': 'intrain',
    'bore chase': 'outtrain',
    'base bike': 'intrain',
    'grand roll': 'outtrain',
    'sail wind': 'intrain',
    'passion wood': 'intrain',
    'center piper': 'outtrain',
    'lighter elf': 'outtrain',
    'south plant': 'intrain',
    'pick sled': 'intrain',
    'barn shaft': 'intrain',
    'chit stuff': 'outtrain',
    'tractor photon': 'outtrain',
    'time port': 'intrain',
    'south mile': 'intrain',
    'kin study': 'outtrain',
    'battle quake': 'intrain',
    'stem hockey': 'outtrain',
    'draw lark': 'intrain',
    'sand stock': 'intrain',
    'head cloth': 'intrain',
    'boat screen': 'intrain',
    'indie punk': 'outtrain',
    'euro linen': 'outtrain',
    'rain pond': 'intrain',
    'cross fish': 'intrain',
    'waist force': 'intrain',
    'hand water': 'intrain',
    'bridge mill': 'intrain',
    'needle leave': 'outtrain',
    'rail hop': 'intrain',
    'home pile': 'intrain',
    'flow beat': 'intrain',
    'husband raid': 'outtrain',
    'wicket dye': 'outtrain',
    'gene tender': 'outtrain',
    'chair bike': 'intrain',
    'norman cam': 'outtrain',
    'fire quake': 'intrain',
    'vicar warp': 'outtrain',
    'fact sail': 'intrain',
    'girl wife': 'intrain',
    'fire mill': 'intrain',
    'command loop': 'outtrain',
    'half writer': 'outtrain',
    'slip mason': 'outtrain',
    'setting oxygen': 'outtrain',
    'dead storey': 'outtrain',
    'window hole': 'intrain',
    'brick shadow': 'intrain',
    'take crest': 'outtrain',
    'goal game': 'intrain',
    'patron stays': 'outtrain',
    'beach stack': 'intrain',
    'torpedo wit': 'outtrain',
    'set boat': 'intrain',
    'saw meat': 'intrain',
    'level trunk': 'outtrain',
    'band hole': 'intrain',
    'sound craft': 'intrain',
    'ship head': 'intrain',
    'slap chord': 'outtrain',
    'web engine': 'outtrain',
    'crank pump': 'outtrain',
    'high robin': 'outtrain',
    'major poster': 'outtrain',
    'techno lapse': 'outtrain',
    'chapter spot': 'outtrain',
    'dish panel': 'outtrain',
    'crew day': 'intrain',
    'chair soil': 'intrain',
    'buffet tide': 'outtrain',
    'school mill': 'intrain',
    'sand ache': 'intrain',
    'music serial': 'outtrain',
    'bed maid': 'intrain',
    'battle note': 'intrain',
    'girl man': 'intrain',
    'white rush': 'outtrain',
    'harvest cycle': 'outtrain',
    'farm flour': 'intrain',
    'boat ship': 'intrain',
    'ship club': 'intrain',
    'toe bridge': 'intrain',
    'number sense': 'outtrain',
    'broad driver': 'outtrain',
    'body girl': 'intrain',
    'copper wood': 'intrain',
    'soul mother': 'outtrain',
    'comic ends': 'outtrain',
    'farm mill': 'intrain',
    'weather sail': 'intrain',
    'process tower': 'outtrain',
    'guess county': 'outtrain',
    'night ship': 'intrain',
    'mile set': 'intrain',
    'sage medal': 'outtrain',
    'rail piece': 'intrain',
    'fort shape': 'outtrain',
    'brick steak': 'intrain',
    'loin robe': 'intrain',
    'sand quake': 'intrain',
    'meadow luck': 'outtrain',
    'band rock': 'intrain',
    'hearth belly': 'outtrain',
    'mast hoe': 'outtrain',
    'byte miner': 'outtrain',
    'cash summer': 'outtrain',
    'beef broker': 'intrain',
    'sea buoy': 'intrain',
    'bob load': 'intrain',
    'rose mill': 'intrain',
    'back boat': 'intrain',
    'hunter poll': 'outtrain',
    'bag street': 'intrain',
    'info finch': 'outtrain',
    'skate band': 'intrain',
    'birth wife': 'intrain',
    'consul son': 'outtrain',
    'milk friend': 'intrain',
    'switch job': 'outtrain',
    'tree soil': 'intrain',
    'use record': 'outtrain',
    'ion riding': 'outtrain',
    'lunch day': 'intrain',
    'win slot': 'outtrain',
    'day fish': 'intrain',
    'saw fuel': 'intrain',
    'tram fill': 'outtrain',
    'special owl': 'outtrain',
    'shop room': 'intrain',
    'rein shine': 'intrain',
    'strait timer': 'outtrain',
    'bubble step': 'outtrain',
    'gilt round': 'outtrain',
    'bog term': 'outtrain',
    'shin click': 'outtrain',
    'cheese road': 'intrain',
    'anchor domain': 'outtrain',
    'hair dress': 'intrain',
    'meeting jar': 'outtrain',
    'sea storm': 'intrain',
    'dance swing': 'outtrain',
    'jet giving': 'outtrain',
    'goal coach': 'intrain',
    'waist set': 'intrain',
    'sand tan': 'intrain',
    'review onset': 'outtrain',
    'wine button': 'outtrain',
    'folk line': 'intrain',
    'school post': 'intrain',
    'fish flour': 'intrain',
    'rifle sale': 'outtrain',
    'wind stack': 'intrain',
    'dove width': 'outtrain',
    'plot curve': 'outtrain',
    'shop house': 'intrain',
    'yard ship': 'intrain',
    'sword bird': 'intrain',
    'lithium pad': 'outtrain',
    'fog solver': 'outtrain',
    'drama fellow': 'outtrain',
    'saw note': 'intrain',
    'launch jerk': 'outtrain',
    'pigeon loss': 'outtrain',
    'log server': 'outtrain',
    'manor lot': 'outtrain',
    'snow mat': 'intrain',
    'cheese meat': 'intrain',
    'pillow lobe': 'outtrain',
    'player swap': 'outtrain',
    'fuel desk': 'intrain',
    'tie fly': 'intrain',
    'word buyer': 'outtrain',
    'run scarf': 'outtrain',
    'lumber mining': 'outtrain',
    'screw decker': 'outtrain',
    'captain vessel': 'outtrain',
    'push lady': 'outtrain',
    'stair line': 'intrain',
    'figure goblin': 'outtrain',
    'ram being': 'outtrain',
    'asylum hiker': 'outtrain',
    'cafe pop': 'outtrain',
    'outside hawk': 'outtrain',
    'boat day': 'intrain',
    'boat car': 'intrain',
    'mean dragon': 'outtrain',
    'jig root': 'outtrain',
    'teacher red': 'outtrain',
    'breadth act': 'outtrain',
    'altar tee': 'outtrain',
    'barn mill': 'intrain',
    'career sort': 'outtrain',
    'prince stitch': 'outtrain',
    'road town': 'intrain',
    'candle cake': 'intrain',
    'ankle cord': 'outtrain',
    'middle action': 'outtrain',
    'fuel coal': 'intrain',
    'road path': 'intrain',
    'holly dealer': 'outtrain',
    'score finish': 'outtrain',
    'fist medium': 'outtrain',
    'trend hen': 'outtrain',
    'spell energy': 'outtrain',
    'drug box': 'intrain',
    'draw block': 'intrain',
    'grass soil': 'intrain',
    'dot deck': 'outtrain',
    'hook people': 'outtrain',
    'lamp foot': 'intrain',
    'form fowl': 'outtrain',
    'dog boat': 'intrain',
    'cloud fit': 'outtrain',
    'october going': 'outtrain',
    'tail mill': 'intrain',
    'square gas': 'outtrain',
    'grave pond': 'intrain',
    'june scotch': 'outtrain',
    'pitch view': 'outtrain',
    'sword right': 'intrain',
    'cloak robe': 'intrain',
    'leg lark': 'intrain',
    'disease louse': 'outtrain',
    'dive essay': 'outtrain',
    'camp end': 'intrain',
    'stand quake': 'intrain',
    'film bed': 'intrain',
    'razor story': 'outtrain',
    'bag power': 'intrain',
    'tow motor': 'outtrain',
    'january caste': 'outtrain',
    'goal man': 'intrain',
    'paint paper': 'intrain',
    'custom dad': 'outtrain',
    'life girl': 'intrain',
    'clergy church': 'outtrain',
    'script flat': 'outtrain',
    'file pit': 'outtrain',
    'fact broker': 'intrain',
    'pack stand': 'intrain',
    'final scorer': 'outtrain',
    'livery world': 'outtrain',
    'trip series': 'outtrain',
    'part brush': 'intrain',
    'contra making': 'outtrain',
    'sword well': 'intrain',
    'censor child': 'outtrain',
    'pill blue': 'outtrain',
    'hog case': 'intrain',
    'cliff sphere': 'outtrain',
    'epoch earner': 'outtrain',
    'wood fish': 'intrain',
    'news yard': 'intrain',
    'wish bolt': 'outtrain',
    'east north': 'outtrain',
    'iron radish': 'outtrain',
    'worm gull': 'intrain',
    'pay copier': 'outtrain',
    'case robe': 'intrain',
    'sand soil': 'intrain',
    'fact soil': 'intrain',
    'thumb bird': 'intrain',
    'snow ice': 'intrain',
    'girl woman': 'intrain',
    'band buoy': 'intrain',
    'alder mind': 'outtrain',
    'folk way': 'intrain',
    'label delay': 'outtrain',
    'fisher dryer': 'outtrain',
    'jelly effect': 'outtrain',
    'plain tennis': 'outtrain',
    'stair room': 'intrain',
    'folk hop': 'intrain',
    'beach kind': 'intrain',
    'ski skiing': 'outtrain',
    'glow seater': 'outtrain',
    'synth make': 'outtrain',
    'cheese meal': 'intrain',
    'task wool': 'outtrain',
    'season league': 'outtrain',
    'gall top': 'intrain',
    'path guard': 'intrain',
    'life bulb': 'intrain',
    'mouse dog': 'intrain',
    'cinema arch': 'outtrain',
    'role order': 'outtrain',
    'time comb': 'intrain',
    'sea flour': 'intrain',
    'flour powder': 'intrain',
    'feast taking': 'outtrain',
    'stair gown': 'intrain',
    'dash second': 'outtrain',
    'drug bed': 'intrain',
    'rip surf': 'outtrain',
    'side quake': 'intrain',
    'pinch share': 'outtrain',
    'wood mill': 'intrain',
    'low think': 'outtrain',
    'news bridge': 'intrain',
    'start shade': 'outtrain',
    'coal line': 'intrain',
    'feather bound': 'outtrain',
    'brick mill': 'intrain',
    'sail ship': 'intrain',
    'cross gear': 'intrain',
    'drive phone': 'outtrain',
    'fighter piece': 'intrain',
    'straw gain': 'outtrain',
    'nick vision': 'outtrain',
    'corner lark': 'intrain',
    'sham lead': 'outtrain',
    'strap jacket': 'outtrain',
    'leather patch': 'outtrain',
    'kill tenant': 'outtrain',
    'draw flight': 'intrain',
    'sugar owner': 'outtrain',
    'waist dress': 'intrain',
    'lark case': 'intrain',
    'dip brace': 'outtrain',
    'head boat': 'intrain',
    'row glider': 'outtrain',
    'maple region': 'outtrain',
    'nit led': 'outtrain',
    'movie teaser': 'outtrain',
    'bishop lily': 'outtrain',
    'safe flower': 'outtrain',
    'neck bulb': 'intrain',
    'ape seed': 'outtrain',
    'god shock': 'outtrain',
    'photo pond': 'intrain',
    'unity pager': 'outtrain',
    'mail soil': 'intrain',
    'waist press': 'intrain',
    'print well': 'intrain',
    'boat sled': 'intrain',
    'tea food': 'intrain',
    'pub result': 'outtrain',
    'short racing': 'outtrain',
    'farm room': 'intrain',
    'font giver': 'outtrain',
    'stair door': 'intrain',
    'chair screen': 'intrain',
    'hair time': 'intrain',
    'bid seeker': 'outtrain',
    'shuffle quest': 'outtrain',
    'centre grouse': 'outtrain',
    'tooth end': 'intrain',
    'snap nickel': 'outtrain',
    'proof shaft': 'intrain',
    'public goon': 'outtrain',
    'stair cloth': 'intrain',
    'crew ship': 'intrain',
    'snow man': 'catch',
    'stone ware': 'catch',
    'tea time': 'catch',
    'sweat band': 'catch',}

class CompoundRelationalJudgment:
    """Relational interpretation of novel compounds, Experiment 2 of Günther &
    Marelli (2022), "Patterns in CAOSS", Cognitive Psychology, 134, 101471.

    Design (ReadMe + paper, Experiment 2, Method, pp. 9-10): 400 participants
    each judged 55 open-form novel compounds - 51 drawn from the pool of 408
    novel compounds plus 4 fixed catch trials (snow man, stone ware, sweat band,
    tea time) - selecting one of 16 relational interpretations per compound.
    The 408 items were randomly arranged into eight experimental lists of 51
    items shown to 50 participants each, and every list carried the same 4
    catch trials.

    The eight lists are recovered from exp0.csv (no list identifier is
    recorded, but the 400 participants' 51-item sets form exactly eight
    disjoint lists that cover the 408 compounds; 49-51 participants each).
    Each simulated participant is assigned one of these lists at random and
    sees its 51 compounds plus the 4 catch items in a random trial order.

    ASSUMPTION: no generative choice model is reported (the core analysis is a
    mapping from semantic vectors to observed relation-frequency distributions,
    not a model of individual choices), so the chosen relation is left entirely
    to the injected ``agent``.

    The response-token policy mirrors ``build_jsonl.py``: each participant gets
    a shuffled 16-letter legend seeded by participant id, and every judgment is
    a free response wrapped in [HUMAN_RESPONSE]...[/HUMAN_RESPONSE].

    The DataFrame matches exp0.csv minus ``rt`` and ``time_elapsed``.
    """

    def __init__(self):
        self.name = "gnther_2022_patterns_exp0"
        self.num_trials = 55          # 51 novel + 4 catch judgments
        self.num_novel = 51
        self.pool = NOVEL             # 408 novel compounds
        self.catch = CATCH            # 4 fixed catch items
        self.lists = LISTS            # eight 51-item lists recovered from exp0.csv

    @staticmethod
    def _legend(pid):
        """Shuffled letter legend seeded by participant id, as build_jsonl.py."""
        codes = [code for code, _ in RELATIONS]
        rng = random.Random(int(str(pid)))
        rng.shuffle(codes)
        return {code: LETTERS[i] for i, code in enumerate(codes)}

    @staticmethod
    def _header(letter_for):
        parts = [
            "You are taking part in a study of how people interpret novel English "
            "compounds: words made of two familiar words combined, which you have "
            "almost certainly never seen before. In each trial you see one such novel "
            "compound written as two words. The FIRST word is the modifier; the SECOND "
            "word is the head. You must choose the one relation that best expresses "
            "what the whole compound means, from sixteen possibilities:"
        ]
        parts += [f"{letter_for[code]}: {dict(RELATIONS)[code]}" for code in letter_for]
        parts += [
            "You answer by typing the letter that names the relation you choose, "
            "e.g. type the single letter next to your chosen relation."
        ]
        return "\n".join(parts)

    def simulate(self, agent, num_simulations, max_chars=None):
        rows, prompts = [], []
        all_letters = list(LETTERS)
        for participant in tqdm(range(num_simulations)):
            pid = int(np.random.randint(100000, 1000000))
            letter_for = self._legend(pid)
            inv = {v: k for k, v in letter_for.items()}
            prompt = self._header(letter_for) + "\n"
            stims = list(self.lists[np.random.randint(len(self.lists))])
            stims = stims + self.catch
            np.random.shuffle(stims)
            age = float(np.random.randint(18, 89))
            gender = str(np.random.choice(
                ["female", "male", "non-binary", "demigirl", "cismale"]))
            for trial, stim in enumerate(stims):
                if max_chars is not None and len(prompt) >= max_chars:
                    break
                prompt += f"You see the novel compound '{stim}'. What does it mean? "
                prompt += "You press [HUMAN_RESPONSE]"
                letter = agent(prompt, choice_options=all_letters)
                code = inv[letter]
                prompt += f"{letter}[/HUMAN_RESPONSE]."
                mod, head = stim.split(" ", 1)
                rows.append({
                    "participant_id": pid, "trial": trial, "response": code,
                    "trial_type": "survey-multi-choice", "trial_index": 5 + trial,
                    "internal_node_id": f"0.0-5.0-0.{trial}",
                    "responses": (f"{mod} {PHRASE[code]} {head}" if code.startswith("M_")
                                  else f"{head} {PHRASE[code]} {mod}"),
                    "question_order": "[0]", "mod": mod, "head": head,
                    "type": STIM_TYPE[stim], "gender_raw": gender, "age": age,
                    "lang": "english", "stim": stim, "comp": stim.replace(" ", ""),
                })
                prompt += "\n"
            prompts.append(prompt.strip())
        df = pd.DataFrame(rows, columns=[
            "participant_id", "trial", "response", "trial_type", "trial_index",
            "internal_node_id", "responses", "question_order", "mod", "head",
            "type", "gender_raw", "age", "lang", "stim", "comp",
        ])
        return df, prompts


def _random_agent(prompt, choice_options):
    return str(np.random.choice(choice_options))


def main():
    parser = argparse.ArgumentParser(
        description="Smoke-test this simulator with a uniform-random agent.")
    parser.add_argument("-n", "--num-simulations", type=int, default=3,
                        help="number of simulated participants (default: 3)")
    parser.add_argument("--max-chars", type=int, default=None,
                        help="stop each participant at the block boundary at/past this many chars")
    parser.add_argument("--seed", type=int, default=None,
                        help="numpy random seed, for reproducible runs")
    args = parser.parse_args()

    if args.seed is not None:
        np.random.seed(args.seed)

    task = CompoundRelationalJudgment()
    df, prompts = task.simulate(_random_agent, args.num_simulations,
                                max_chars=args.max_chars)

    print(f"name: {task.name}")
    print(f"df shape: {df.shape}")
    print("dtypes:")
    print(df.dtypes.to_string())
    print("head:")
    print(df.head(8).to_string())
    print(f"prompt lengths: {[len(p) for p in prompts]}")
    for i, p in enumerate(prompts):
        first = p.splitlines()[0]
        if len(first) > 180:
            first = first[:90] + " … " + first[-90:]
        print(f"participant {i} first line: {first}")
    print("=" * 78)
    print("first prompt, head:")
    print(prompts[0][:600])
    print("...")
    print("first prompt, tail:")
    print(prompts[0][-300:])


if __name__ == "__main__":
    main()
